// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yogenyslav/ya-metrics/internal/server/handler (interfaces: auditLogger)
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/mocks/audit.go -package=mocks . auditLogger
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockauditLogger is a mock of auditLogger interface.
type MockauditLogger struct {
	ctrl     *gomock.Controller
	recorder *MockauditLoggerMockRecorder
	isgomock struct{}
}

// MockauditLoggerMockRecorder is the mock recorder for MockauditLogger.
type MockauditLoggerMockRecorder struct {
	mock *MockauditLogger
}

// NewMockauditLogger creates a new mock instance.
func NewMockauditLogger(ctrl *gomock.Controller) *MockauditLogger {
	mock := &MockauditLogger{ctrl: ctrl}
	mock.recorder = &MockauditLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauditLogger) EXPECT() *MockauditLoggerMockRecorder {
	return m.recorder
}

// LogMetrics mocks base method.
func (m *MockauditLogger) LogMetrics(ctx context.Context, metrics []string, ipAddr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogMetrics", ctx, metrics, ipAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogMetrics indicates an expected call of LogMetrics.
func (mr *MockauditLoggerMockRecorder) LogMetrics(ctx, metrics, ipAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogMetrics", reflect.TypeOf((*MockauditLogger)(nil).LogMetrics), ctx, metrics, ipAddr)
}
