// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yogenyslav/ya-metrics/pkg/database (interfaces: PostgresTxDB)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockPostgresTxDB is a mock of PostgresTxDB interface.
type MockPostgresTxDB struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresTxDBMockRecorder
}

// MockPostgresTxDBMockRecorder is the mock recorder for MockPostgresTxDB.
type MockPostgresTxDBMockRecorder struct {
	mock *MockPostgresTxDB
}

// NewMockPostgresTxDB creates a new mock instance.
func NewMockPostgresTxDB(ctrl *gomock.Controller) *MockPostgresTxDB {
	mock := &MockPostgresTxDB{ctrl: ctrl}
	mock.recorder = &MockPostgresTxDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresTxDB) EXPECT() *MockPostgresTxDBMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockPostgresTxDB) BeginTx(arg0 context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", arg0)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockPostgresTxDBMockRecorder) BeginTx(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockPostgresTxDB)(nil).BeginTx), arg0)
}

// Close mocks base method.
func (m *MockPostgresTxDB) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockPostgresTxDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPostgresTxDB)(nil).Close))
}

// Exec mocks base method.
func (m *MockPostgresTxDB) Exec(arg0 context.Context, arg1 string, arg2 ...interface{}) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockPostgresTxDBMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockPostgresTxDB)(nil).Exec), varargs...)
}

// Ping mocks base method.
func (m *MockPostgresTxDB) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPostgresTxDBMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPostgresTxDB)(nil).Ping), arg0)
}

// QueryRow mocks base method.
func (m *MockPostgresTxDB) QueryRow(arg0 context.Context, arg1 interface{}, arg2 string, arg3 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockPostgresTxDBMockRecorder) QueryRow(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockPostgresTxDB)(nil).QueryRow), varargs...)
}

// QuerySlice mocks base method.
func (m *MockPostgresTxDB) QuerySlice(arg0 context.Context, arg1 interface{}, arg2 string, arg3 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QuerySlice", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// QuerySlice indicates an expected call of QuerySlice.
func (mr *MockPostgresTxDBMockRecorder) QuerySlice(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySlice", reflect.TypeOf((*MockPostgresTxDB)(nil).QuerySlice), varargs...)
}

// SQLDB mocks base method.
func (m *MockPostgresTxDB) SQLDB() (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SQLDB")
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SQLDB indicates an expected call of SQLDB.
func (mr *MockPostgresTxDBMockRecorder) SQLDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SQLDB", reflect.TypeOf((*MockPostgresTxDB)(nil).SQLDB))
}
