// Code generated by reset generator; DO NOT EDIT.

package model

func (x *Metrics[T]) Reset() {
	x.ID = ""
	x.Type = ""
	x.Value = *new(T)
}

func (x *MetricsDto) Reset() {
	x.ID = ""
	x.Type = ""
	x.Value = nil
	x.Delta = nil
}

