// Code generated by reset generator; DO NOT EDIT.

package collector

func (x *MemoryMetrics) Reset() {
	x.Alloc.Reset()
	x.BuckHashSys.Reset()
	x.Frees.Reset()
	x.GCCPUFraction.Reset()
	x.GCSys.Reset()
	x.HeapAlloc.Reset()
	x.HeapIdle.Reset()
	x.HeapInuse.Reset()
	x.HeapObjects.Reset()
	x.HeapReleased.Reset()
	x.HeapSys.Reset()
	x.LastGC.Reset()
	x.Lookups.Reset()
	x.MCacheInuse.Reset()
	x.MCacheSys.Reset()
	x.MSpanInuse.Reset()
	x.MSpanSys.Reset()
	x.Mallocs.Reset()
	x.NextGC.Reset()
	x.NumForcedGC.Reset()
	x.NumGC.Reset()
	x.OtherSys.Reset()
	x.PauseTotalNs.Reset()
	x.StackInuse.Reset()
	x.StackSys.Reset()
	x.Sys.Reset()
	x.TotalAlloc.Reset()
}

func (x *GeneralMetrics) Reset() {
	x.PollCount.Reset()
	x.RandomValue.Reset()
}

func (x *UtilizationMetrics) Reset() {
	x.TotalMemory.Reset()
	x.FreeMemory.Reset()
	x.CPUUtilization = x.CPUUtilization[:0]
}

